### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by larsbutler** [aws/amazon-linux-docker-images#1]
If Amazon Linux Docker artifacts are intended to be used by others, an open source license should be explicitly declared in the repo. It's also helpful to use [Dockerfile LABEL directives](https://docs.docker.com/engine/reference/builder/#label) to include license metadata with built images.

**Comment by larsbutler** [comment]
Also, thanks for making this stuff available! :)

**Comment by praveen-pk** [comment]
I just pushed a license file to this repository. Closing this issue.
