### ISSUE TITLE
AWS CLI?

### ISSUE THREAD

**Issue by iancward** [aws/amazon-linux-docker-images#10]
The Docker Hub page for this image makes the following claim:
> It also includes packages that enable easy integration with AWS, including launch configuration tools and many popular AWS libraries and tools

But, the AWS CLI isn't included. I believe the off-the-shelf Amazon Linux AMIs contain the AWS CLI so it's surprising that this doesn't. Can it be included?

**Comment by ilianaw** [comment]
`yum install aws-cli` on Amazon Linux 2018.03 or `yum install awscli` on Amazon Linux 2.

The Docker images are deliberately small and only includes what is needed to use yum, basically. If we included AWS CLI, every single user of the image would need to transfer it / have it on disk whether or not they're using it.

**Comment by iancward** [comment]
@ilianaw thanks for the clarification.
Is there any hope for an "official" docker image that includes the AWS CLI? It looks like there are several "unofficial" images that attempt to provide it, but it would be great if there was an official image for AWS CLI for CI/CD purposes.

Thanks.

**Comment by ilianaw** [comment]
@iancward I think that's a good idea but ultimately I think that decision is up to the AWS CLI maintainers.

I'll suggest the idea to them.
