### ISSUE TITLE
Are these images supposed to be similar to those deployed using the EC2?

### ISSUE THREAD

**Issue by tbys** [aws/amazon-linux-docker-images#11]
I'm trying to build a Docker container to run Greengrass Core, but what I get with `FROM:amazonlinux:2017.12.0.20180330-with-sources` is radically different than what I get when deploying an EC2 instance with the Amazon Linux AMI image.

The Greengrass Core dependency checker fails on numerous items.

Notably I've had to install `binutils`, `shadow-utils`, `findutils`.

Is this normal? Am I using the wrong Docker container?

**Comment by praveen-pk** [comment]
The Amazon Linux container images published on docker.io are much slimmer than the AMIs published in EC2. So what you reported is normal.

Also, FYI, the images with '-with-sources' in the tag have source rpms placed in the image. If you don't use the source rpms in the image, you can use amazonlinux:2017.12 container image.

**Comment by tbys** [comment]
Good to know, thank you for the answer @praveen-pk.
