### ISSUE TITLE
Please pre-install sudo

### ISSUE THREAD

**Issue by Nuru** [aws/amazon-linux-docker-images#13]
OK, I understand the image is stripped down, and `sudo` is not strictly necessary since the base image has no interactive user other than `root`, but still, not having `sudo` installed breaks scripts and tutorials. For example, the [official Docker repo](https://hub.docker.com/_/amazonlinux/) includes this documentation:

> ### How do I install a software package from Extras repository in Amazon Linux 2?
> Available packages can be listed with the amazon-linux-extras command. Packages can be installed with the `sudo amazon-linux-extras install <package>` command. Example: `sudo amazon-linux-extras install rust1`

Elsewhere on the web, documentation for adding EPEL says
```
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -P /tmp
sudo yum install -y /tmp/epel-release-latest-7.noarch.rpm
```
There are many other examples. Not having `sudo` installed not only made things (slightly) more difficult, but more importantly made me seriously question if I was using the right image of if somehow the image was corrupted. 

Please also document more prominently that this Docker image is heavily stripped down compared to the full AMI. If feasible, provide a list of packages to install in order to reach parity with the full AMI.

**Comment by jahkeup** [comment]
Hi @Nuru, I'm sorry the missing `sudo` command was problematic for your uses. The absence of the `sudo` is common place in the container ecosystem, many container images default to running as the root user. In most cases this translates into dropping `sudo` from commands and often downstream  Dockerfiles will include a statement specifying another user for runtime. To install the EPEL repository interactively you could run `yum install https://.../epel-release-latest-7.noarch.rpm` in the container, or add the equivalent line to your Dockerfile.

There is certain balance in minimization that must be had to make container images useful in the context of containerized applications, which comes at the cost of trimmed out uncommon or unneeded packages. If you require additional packages that are not installed, `yum` can install these as you would with an instance running the Amazon Linux 2 AMI. In fact,` yum`'s Package Groups are used to target a specific Amazon Linux 2 "flavor", so you can see the difference in packages (or install them with `groupinstall`) like so:

```bash
$ docker run amazonlinux:2 sh -c 'yum makecache && yum groupinfo base-minimal'                                                                          
Loaded plugins: ovl, priorities
Metadata Cache Created
Loaded plugins: ovl, priorities
There is no installed groups file.
Maybe run: yum groups mark convert (see man yum)

Group: Base (minimal)
 Group-Id: base-minimal
 Description: The basic minimal install of Amazon Linux.
 Mandatory Packages:
    amazon-linux-extras
   +audit
   +authconfig
    basesystem
    bash
    ca-certificates
   +chrony
   +cloud-utils-growpart
    coreutils
   +cronie
   +dhclient
   +dracut-config-generic
   +gdisk
   +glibc-all-langpacks
   +glibc-locale-source
   +grub2
   +initscripts
   +iproute
   +iptables
   +iputils
   +irqbalance
   +kernel
   +less
   +man-db
   +openssh-clients
   +openssh-server
   +passwd
   +policycoreutils
   +postfix
   +procps-ng
   +psmisc
   +rng-tools
   +rootfiles
   +rpm-plugin-systemd-inhibit
   +rsyslog
   +selinux-policy-targeted
    setup
   +shadow-utils
   +sudo
    system-release
   +systemd
   +tar
   +update-motd
   +util-linux
    vim-minimal
   +xfsprogs
    yum
    yum-plugin-priorities

```

That said, the documentation on the Docker Hub page will need an update - those instructions are inaccurate when using the Amazon Linux 2 container image. I'll reach out to the appropriate folks and make sure that happens.

**Comment by jahkeup** [comment]
The package groups are marked as invisible and so are omitted when queried with `yum grouplist` or `yum grouplist available`. To get all groups known by `yum`, you can call `yum grouplist hidden`, which will return the entire list of package groups, ignoring their metadata:

```bash
# yum grouplist hidden
Loaded plugins: langpacks, ovl, priorities, update-motd
Installed Groups:
   Base
   Container
Available Groups:
   AMI
   AMI (minimal)
   AWS Tools
   Base (minimal)
   Core
   Development Tools
   OnPrem
   OnPrem (minimal)
Done
```

To get some more info for these groups you can call `yum groupinfo` with the name (ie: `yum groupinfo "AMI (minimal)"`).

Please note: these groups _are stable for use_ and will be made visible by default in a future repo update.

**Comment by jahkeup** [comment]
The documentation on the [Docker Hub page](https://hub.docker.com/_/amazonlinux/) has been updated and no longer refers to the commands with `sudo`.
