### ISSUE TITLE
why not update lastest to 2.0.20181114

### ISSUE THREAD

**Issue by gnuhub** [aws/amazon-linux-docker-images#17]
https://cdn.amazonlinux.com/os-images/2.0.20181114/container/
@ilianaw

**Comment by ilianaw** [comment]
We aren't ready to release these changes to the official images repositories yet, sorry.

I'll keep this issue open until we do.

**Comment by ilianaw** [comment]
It's been merged: https://github.com/docker-library/official-images/pull/5108

The images will push out to Docker Hub over the next hour or so. Thanks for your patience.
