### ISSUE TITLE
Error Message: standard_init_linux.go:190: exec user process caused "no such file or directory" 

### ISSUE THREAD

**Issue by bobbyc** [aws/amazon-linux-docker-images#18]
Hi,

I got following error when I am trying to build arm64v8 docker image on Ubuntu 16.04 x64 and macOS x64. I already installed qemu-related package on ubuntu. However, I still have the error. Could someone help on this? Thanks.

============
Error Message

Step 1/3 : FROM arm64v8/amazonlinux:2
2: Pulling from arm64v8/amazonlinux
95dc14c8379b: Pull complete
Digest: sha256:51a7fb7327cf75dd4175c1030af8107ebe8fd78d1660c0a19ca847e6091dfcf2
Status: Downloaded newer image for arm64v8/amazonlinux:2
 ---> 05fb2032e6e1
Step 2/3 : COPY qemu-arm-static /usr/bin/qemu-arm-static
 ---> 30f151c40a37
Step 3/3 : RUN echo Hello from ARM container
 ---> Running in a8b0b64b9f08
standard_init_linux.go:190: exec user process caused "no such file or directory"

**Comment by ilianaw** [comment]
You won’t be able to run commands for an arm64v8 container on an amd64 host.

**Comment by bobbyc** [comment]
@ilianaw Thanks. In the end, I found the solution from qemu user-mode emulation. I should use qemu-aarch64-static instead of qemu-arm-static in my docker images.

**Comment by ilianaw** [comment]
Glad to hear! Let us know if you run into any other issues.

**Comment by ro-tex** [comment]
@bobbyc Thank you so much for coming back and sharing that gold nugget of a tip! 
You are my hero!
