### ISSUE TITLE
Need groff package to view aws-cli docs

### ISSUE THREAD

**Issue by psftw** [aws/amazon-linux-docker-images#2]
After installing the `aws-cli` package, but before manually installing `groff`:

```
bash-4.2# aws help

Could not find executable named "groff"
```

I would imagine using `aws-cli` will be a common workflow, and you can just mount in `~/.aws` to address different accounts nicely.  Looks like `aws-cli` is 32MB (and `groff` is ~7MB) so I understand if you don't want to ship these by default.

**Comment by ianweller** [comment]
We're hoping to keep the base image minimal like most other base images.

Something that might make more sense is adding groff as a `Requires` on aws-cli. We're going to look into doing that for a future repo push.

Thanks for the feedback! (I'm going to keep this issue open until we change aws-cli in our repos.)

**Comment by ianweller** [comment]
As of the repository push a few hours ago, aws-cli was updated to include a `Requires` on groff. (aws-cli was also updated to 1.11.17.)

**Comment by MonkeyTonk** [comment]
With version 1.11.36 of the bundled installer I am still getting
`Could not find executable named "groff"`
for
`aws help`
