### ISSUE TITLE
Update repository access

### ISSUE THREAD

**Issue by veselov** [aws/amazon-linux-docker-images#25]
The version 2 image comes with only `amzn2-core.repo`, which, I guess, contains the default packages. But update repository is not configured. My attempts to guess what the URLs are for it have failed. For version 1, some packages are only available in the update repository, and are not provided in the main repository at all (e.g. cmake3). Without that, it's somewhat hard to be able to use the docker image the same way that one would use the system in AWS cloud...

From docker.io/amazonlinux:latest:
```
yum list | grep cmake
cmake.x86_64                           2.8.12.2-2.amzn2.0.2           amzn2-core
cmake-gui.x86_64                       2.8.12.2-2.amzn2.0.2           amzn2-core

```
From container docker.io/amazonlinux:1:
```
yum list|grep cmake
cmake.x86_64                          2.8.12.2-4.25.amzn1           amzn-main   
cmake-doc.x86_64                      2.8.12.2-4.25.amzn1           amzn-main   
cmake3.x86_64                         3.6.1-3.0.amzn1               amzn-updates
cmake3-data.noarch                    3.6.1-3.0.amzn1               amzn-updates
cmake3-doc.noarch                     3.6.1-3.0.amzn1               amzn-updates
```

**Comment by ilianaw** [comment]
There is no main/updates split in Amazon Linux 2. Packages not belonging to core are available in "extras", which you can configure with `amazon-linux-extras`.

cmake3 isn't available in AL2 core. You can install a version of it from the rust1 extra right now, which is not terribly obvious. I'll check to see if we have plans for cmake3 I can share.

**Comment by ilianaw** [comment]
I confirmed internally that we're planning on adding cmake3 to core soon. I'll try to update this issue when it does ultimately get pushed. Thanks!
