### ISSUE TITLE
upload image for aws lambda compatible 2016.03 ami

### ISSUE THREAD

**Issue by ahmetkizilay** [aws/amazon-linux-docker-images#3]
As specified [here](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) AWS Lambda is using amzn-ami-hvm-2016.03.3.x86_64-gp2. 

Can you publish an image for this AMI?

Thanks

**Comment by ilianaw** [comment]
The 2016.09 release is *very* similar to 2016.03. We believe that the 2016.09 container image is sufficient for building Lambda functions (we've been using it for lots of ours).

Are you running into any incompatibility issues?

**Comment by ahmetkizilay** [comment]
In my case, I am running curl scripts and parse the output messages. curl and openssl versions are different between two images, so I get different output messages between my test and prod environments.
