### ISSUE TITLE
aws ami docker image differences

### ISSUE THREAD

**Issue by fernandoaleman** [aws/amazon-linux-docker-images#4]
I am new to the amazon ami docker images. When I spin up the ami docker image, I notice that things that are normally already installed on the ami on aws when I spin up a new ec2 server are missing. For example, aws cli tools, ec2-user etc. I understand things work a bit differently with docker, but was hoping to simulate a similar environment for testing locally. So just curious, why were these excluded? Thank you!

**Comment by praveen-pk** [comment]
Docker images are usually kept minimal for quick downloads. We also installed minimal set of packages in amazon linux's docker images to keep the image size as small as possible. 

You can either install the packages you need at/after startup of amazon linux container or you can create a new docker image yourself with all extra packages you need.

**Comment by fernandoaleman** [comment]
@praveen-pk  Ok, that makes sense. So basically, if I install aws cli tools, java, python, ruby and create an ec2-user, it should be the same as the ami image on aws?

**Comment by praveen-pk** [comment]
yes, that is correct. I am not sure how you are using the ec2-user account. But, the amazon linux docker images and amis are configured with the same set of yum repositories. So, you will end up with the same set of packages in both cases.

**Comment by fernandoaleman** [comment]
Excellent, thank you @praveen-pk 👍
