### ISSUE TITLE
Python 3 ?

### ISSUE THREAD

**Issue by vincentsarago** [aws/amazon-linux-docker-images#5]
Is there a timeline for an update of the amazonlinux AMI with python 3.6 ?

Thanks

**Comment by ilianaw** [comment]
We can't provide dates or timelines on when features will become available, but Python 3.6 is on our roadmap.

It won't be included in the Docker image but you'll be able to get it with yum when it's available. Keep an eye on [the forums](https://forums.aws.amazon.com/forum.jspa?forumID=228) for an announcement.
