### ISSUE TITLE
2017.03.1 Point Release?

### ISSUE THREAD

**Issue by ankon** [aws/amazon-linux-docker-images#6]
According to https://aws.amazon.com/amazon-linux-ami/2017.03-release-notes/ there was a 2017.03.1 point release, could you update this repository as well?

From what I understand one can use `yum update` in the container to get to that state. In our case we build further images on top, and it would be nice for our CI speeds to avoid some of the yum traffic :)

**Comment by ilianaw** [comment]
I believe at the time 2017.03.1 came out there weren't any significant updates in the container image to warrant publishing a new one.

That has changed, and we have one prepped that I'm hoping to test and publish soon.

**Comment by ilianaw** [comment]
A 2017.03.1 image was published to Docker Hub today (https://github.com/docker-library/official-images/pull/3384).
