### ISSUE TITLE
Upload image for full Amazon Linux AMI

### ISSUE THREAD

**Issue by ilons** [aws/amazon-linux-docker-images#7]
When testing modifications to scripts used to build AMI's, its often desired to build locally to speed up the feedback loop (booting and connecting to an EC2 instance take some time).

Due to the slim profile of the image currently built and published, it is very hard to use for this purpose, and it would be great to have if you could publish a full docker image replica of the AMI published on EC2.

Would it be possible for you to provide an image for the full AMI?

**Comment by praveen-pk** [comment]
Maintaining two different images, minimal and non-minimal, would cause additional operational load for us. You can create create custom docker image for your needs based on our minimal image and use that for your local testing.

Are you running into any challenges with creating a custom image?
